version: "3.8"

services:
  notification-service:
    container_name: notification-service
    build: .
    ports:
      - "3001:3001"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    env_file:
      - .env
